@echo off
echo Downloading 15 Constellation Artworks...
set PS="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
set BASE=https://raw.githubusercontent.com/Stellarium/stellarium-skycultures/master/western/illustrations
set DST=F:\build\stardroid\app\src\main\assets\constellation_artwork
echo.
echo Downloading andromeda...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/andromeda.webp' -OutFile '%DST%\andromeda.webp'"
echo.
echo Downloading bootes...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/bootes.webp' -OutFile '%DST%\bootes.webp'"
echo.
echo Downloading cassiopeia...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/cassiopeia.webp' -OutFile '%DST%\cassiopeia.webp'"
echo.
echo Downloading cygnus...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/cygnus.webp' -OutFile '%DST%\cygnus.webp'"
echo.
echo Downloading gemini...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/gemini.webp' -OutFile '%DST%\gemini.webp'"
echo.
echo Downloading canis_major...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/canis-major.webp' -OutFile '%DST%\canis-major.webp'"
echo.
echo Downloading ursa_major...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/ursa-major.webp' -OutFile '%DST%\ursa-major.webp'"
echo.
echo Downloading leo...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/leo.webp' -OutFile '%DST%\leo.webp'"
echo.
echo Downloading orion...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/orion.webp' -OutFile '%DST%\orion.webp'"
echo.
echo Downloading pegasus...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/pegasus.webp' -OutFile '%DST%\pegasus.webp'"
echo.
echo Downloading ursa_minor...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/ursa-minor.webp' -OutFile '%DST%\ursa-minor.webp'"
echo.
echo Downloading sagittarius...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/sagittarius.webp' -OutFile '%DST%\sagittarius.webp'"
echo.
echo Downloading scorpius...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/scorpius.webp' -OutFile '%DST%\scorpius.webp'"
echo.
echo Downloading taurus...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/taurus.webp' -OutFile '%DST%\taurus.webp'"
echo.
echo Downloading virgo...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/virgo.webp' -OutFile '%DST%\virgo.webp'"
echo.
echo All backgrounds updated successfully!
pause