@echo off
echo Downloading 15 Constellation Artworks...
set PS="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
set BASE=https://raw.githubusercontent.com/Stellarium/stellarium-skycultures/master/western/illustrations
set DST=F:\build\stardroid\app\src\main\assets\constellation_artwork
echo.
echo Downloading aql...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/aquila.webp' -OutFile '%DST%\aquila.webp'"
echo.
echo Downloading andromeda...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/andromeda.webp' -OutFile '%DST%\andromeda.webp'"
echo.
echo Downloading scl...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/sculptor.webp' -OutFile '%DST%\sculptor.webp'"
echo.
echo Downloading ara...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/ara.webp' -OutFile '%DST%\ara.webp'"
echo.
echo Downloading lib...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/libra.webp' -OutFile '%DST%\libra.webp'"
echo.
echo Downloading cet...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/cetus.webp' -OutFile '%DST%\cetus.webp'"
echo.
echo Downloading ari...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/aries.webp' -OutFile '%DST%\aries.webp'"
echo.
echo Downloading sct...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/scutum.webp' -OutFile '%DST%\scutum.webp'"
echo.
echo Downloading pyx...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/pyxis.webp' -OutFile '%DST%\pyxis.webp'"
echo.
echo Downloading bootes...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/bootes.webp' -OutFile '%DST%\bootes.webp'"
echo.
echo Downloading cae...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/caelum.webp' -OutFile '%DST%\caelum.webp'"
echo.
echo Downloading cha...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/chamaeleon.webp' -OutFile '%DST%\chamaeleon.webp'"
echo.
echo Downloading cnc...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/cancer.webp' -OutFile '%DST%\cancer.webp'"
echo.
echo Downloading cap...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/capricornus.webp' -OutFile '%DST%\capricornus.webp'"
echo.
echo Downloading car...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/argonavis.webp' -OutFile '%DST%\argonavis.webp'"
echo.
echo Downloading cassiopeia...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/cassiopeia.webp' -OutFile '%DST%\cassiopeia.webp'"
echo.
echo Downloading cen...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/centaurus.webp' -OutFile '%DST%\centaurus.webp'"
echo.
echo Downloading cep...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/cepheus.webp' -OutFile '%DST%\cepheus.webp'"
echo.
echo Downloading com...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/coma-berenices.webp' -OutFile '%DST%\coma-berenices.webp'"
echo.
echo Downloading cvn...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/canes-venatici.webp' -OutFile '%DST%\canes-venatici.webp'"
echo.
echo Downloading aur...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/auriga.webp' -OutFile '%DST%\auriga.webp'"
echo.
echo Downloading col...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/columba.webp' -OutFile '%DST%\columba.webp'"
echo.
echo Downloading cir...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/circinus.webp' -OutFile '%DST%\circinus.webp'"
echo.
echo Downloading crt...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/crater.webp' -OutFile '%DST%\crater.webp'"
echo.
echo Downloading cra...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/corona-australis.webp' -OutFile '%DST%\corona-australis.webp'"
echo.
echo Downloading crb...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/corona-borealis.webp' -OutFile '%DST%\corona-borealis.webp'"
echo.
echo Downloading crv...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/corvus.webp' -OutFile '%DST%\corvus.webp'"
echo.
echo Downloading cru...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/crux.webp' -OutFile '%DST%\crux.webp'"
echo.
echo Downloading cygnus...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/cygnus.webp' -OutFile '%DST%\cygnus.webp'"
echo.
echo Downloading del...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/delphinus.webp' -OutFile '%DST%\delphinus.webp'"
echo.
echo Downloading dor...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/dorado.webp' -OutFile '%DST%\dorado.webp'"
echo.
echo Downloading dra...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/draco.webp' -OutFile '%DST%\draco.webp'"
echo.
echo Downloading nor...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/norma.webp' -OutFile '%DST%\norma.webp'"
echo.
echo Downloading eri...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/eridanus.webp' -OutFile '%DST%\eridanus.webp'"
echo.
echo Downloading sge...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/sagitta.webp' -OutFile '%DST%\sagitta.webp'"
echo.
echo Downloading for...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/fornax.webp' -OutFile '%DST%\fornax.webp'"
echo.
echo Downloading gemini...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/gemini.webp' -OutFile '%DST%\gemini.webp'"
echo.
echo Downloading cam...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/camelopardalis.webp' -OutFile '%DST%\camelopardalis.webp'"
echo.
echo Downloading canis_major...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/canis-major.webp' -OutFile '%DST%\canis-major.webp'"
echo.
echo Downloading ursa_major...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/ursa-major.webp' -OutFile '%DST%\ursa-major.webp'"
echo.
echo Downloading gru...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/grus.webp' -OutFile '%DST%\grus.webp'"
echo.
echo Downloading her...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/hercules.webp' -OutFile '%DST%\hercules.webp'"
echo.
echo Downloading hor...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/horlogium.webp' -OutFile '%DST%\horlogium.webp'"
echo.
echo Downloading hya...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/hydra.webp' -OutFile '%DST%\hydra.webp'"
echo.
echo Downloading hyi...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/hydrus.webp' -OutFile '%DST%\hydrus.webp'"
echo.
echo Downloading ind...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/indus.webp' -OutFile '%DST%\indus.webp'"
echo.
echo Downloading lac...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/lacerta.webp' -OutFile '%DST%\lacerta.webp'"
echo.
echo Downloading mon...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/monoceros.webp' -OutFile '%DST%\monoceros.webp'"
echo.
echo Downloading lep...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/lepus.webp' -OutFile '%DST%\lepus.webp'"
echo.
echo Downloading leo...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/leo.webp' -OutFile '%DST%\leo.webp'"
echo.
echo Downloading lup...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/lupus.webp' -OutFile '%DST%\lupus.webp'"
echo.
echo Downloading lyn...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/lynx.webp' -OutFile '%DST%\lynx.webp'"
echo.
echo Downloading lyr...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/lyra.webp' -OutFile '%DST%\lyra.webp'"
echo.
echo Downloading ant...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/antlia.webp' -OutFile '%DST%\antlia.webp'"
echo.
echo Downloading mic...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/microscopium.webp' -OutFile '%DST%\microscopium.webp'"
echo.
echo Downloading mus...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/musca.webp' -OutFile '%DST%\musca.webp'"
echo.
echo Downloading oct...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/octans.webp' -OutFile '%DST%\octans.webp'"
echo.
echo Downloading aps...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/apus.webp' -OutFile '%DST%\apus.webp'"
echo.
echo Downloading oph...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/ophiuchus.webp' -OutFile '%DST%\ophiuchus.webp'"
echo.
echo Downloading orion...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/orion.webp' -OutFile '%DST%\orion.webp'"
echo.
echo Downloading pav...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/pavo.webp' -OutFile '%DST%\pavo.webp'"
echo.
echo Downloading pegasus...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/pegasus.webp' -OutFile '%DST%\pegasus.webp'"
echo.
echo Downloading pic...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/pictor.webp' -OutFile '%DST%\pictor.webp'"
echo.
echo Downloading per...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/perseus.webp' -OutFile '%DST%\perseus.webp'"
echo.
echo Downloading equ...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/equuleus.webp' -OutFile '%DST%\equuleus.webp'"
echo.
echo Downloading cmi...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/canis-minor.webp' -OutFile '%DST%\canis-minor.webp'"
echo.
echo Downloading lmi...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/leo-minor.webp' -OutFile '%DST%\leo-minor.webp'"
echo.
echo Downloading vul...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/vulpecula.webp' -OutFile '%DST%\vulpecula.webp'"
echo.
echo Downloading ursa_minor...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/ursa-minor.webp' -OutFile '%DST%\ursa-minor.webp'"
echo.
echo Downloading phe...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/phoenix.webp' -OutFile '%DST%\phoenix.webp'"
echo.
echo Downloading psc...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/pisces.webp' -OutFile '%DST%\pisces.webp'"
echo.
echo Downloading psa...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/piscis-austrinus.webp' -OutFile '%DST%\piscis-austrinus.webp'"
echo.
echo Downloading vol...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/volans.webp' -OutFile '%DST%\volans.webp'"
echo.
echo Downloading ret...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/reticulum.webp' -OutFile '%DST%\reticulum.webp'"
echo.
echo Downloading sagittarius...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/sagittarius.webp' -OutFile '%DST%\sagittarius.webp'"
echo.
echo Downloading scorpius...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/scorpius.webp' -OutFile '%DST%\scorpius.webp'"
echo.
echo Downloading sex...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/sextans.webp' -OutFile '%DST%\sextans.webp'"
echo.
echo Downloading men...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/mensa.webp' -OutFile '%DST%\mensa.webp'"
echo.
echo Downloading taurus...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/taurus.webp' -OutFile '%DST%\taurus.webp'"
echo.
echo Downloading tel...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/telescopium.webp' -OutFile '%DST%\telescopium.webp'"
echo.
echo Downloading tuc...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/tucana.webp' -OutFile '%DST%\tucana.webp'"
echo.
echo Downloading tri...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/triangulum.webp' -OutFile '%DST%\triangulum.webp'"
echo.
echo Downloading tra...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/triangulum-australe.webp' -OutFile '%DST%\triangulum-australe.webp'"
echo.
echo Downloading aqr...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/aquarius.webp' -OutFile '%DST%\aquarius.webp'"
echo.
echo Downloading virgo...
%PS% -Command "Invoke-WebRequest -Uri '%BASE%/virgo.webp' -OutFile '%DST%\virgo.webp'"
echo.
echo All backgrounds updated successfully!
pause